server:
  name: congfig_test
  author: airing
  version: 1.0
  port: 8080

log:
  level: debug
  path: ../log/
  maxSize: 100   #mb
  maxBackups: 20 #file count
  maxAge: 30     #days
  compress: true

redis_test:
  addr: xxx.xxx.xxx.xxx:6379
  password: test

mysql_test:
  addr: xxx.xxx.xxx.xxx:6379
  user: test_user
  password: test